spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: yourAccessKey
      secret-key: yourSecretKey
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-demo-aries
server:
  port: 8003
